name: bilgi_rotasi
description: Aynı telefonda 2-6 kişilik Türkçe bilgi yarışması.
publish_to: "none"
version: 1.11.2+14

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  audioplayers: ^6.8.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/pawns/
    - assets/questions.json
