name: bilgi_rotasi
description: Aynı telefonda 2-6 kişilik Türkçe bilgi yarışması.
publish_to: "none"
version: 1.6.0+7

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/questions.json
