name: bilgi_rotasi
description: "A new Flutter project."
publish_to: 'none'
version: 1.68.17+107

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  flutter_tts: ^4.2.3
  google_mobile_ads: ^6.0.0
  firebase_core: ^4.2.1
  firebase_analytics: ^12.0.4
  firebase_crashlytics: ^5.0.4
  firebase_messaging: ^16.0.4
  audioplayers: ^6.5.1
  http: ^1.5.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/questions.json
    - assets/sounds/
    - assets/audio/questions/
    - assets/word_hunt/baslangic_limani_bg.webp

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icon/bilgi_rotasi_logo.png
  adaptive_icon_background: "#1A237E"
  adaptive_icon_foreground: assets/icon/bilgi_rotasi_logo.png
  min_sdk_android: 23
