import 'word_hunt_models.dart';

class WordHuntStarterContent {
  WordHuntStarterContent._();

  static const List<WordHuntInfoCard> infoCards = <WordHuntInfoCard>[
    WordHuntInfoCard(
      id: 'info-deniz',
      word: 'DENİZ',
      title: 'Deniz',
      shortFact: 'Deniz suyu, çözünmüş tuzlar nedeniyle genellikle tuzludur.',
      category: 'Doğa',
    ),
    WordHuntInfoCard(
      id: 'info-kitap',
      word: 'KİTAP',
      title: 'Kitap',
      shortFact: 'Kitaplar bilgi, öykü ve fikirleri kalıcı olarak aktarmanın yollarından biridir.',
      category: 'Kültür',
    ),
    WordHuntInfoCard(
      id: 'info-ankara',
      word: 'ANKARA',
      title: 'Ankara',
      shortFact: 'Ankara, Türkiye’nin başkentidir.',
      category: 'Türkiye',
    ),
    WordHuntInfoCard(
      id: 'info-ari',
      word: 'ARI',
      title: 'Arı',
      shortFact: 'Arılar, birçok çiçekli bitkinin tozlaşmasına yardımcı olur.',
      category: 'Doğa',
    ),
    WordHuntInfoCard(
      id: 'info-mars',
      word: 'MARS',
      title: 'Mars',
      shortFact: 'Mars, Güneş’e uzaklık bakımından dördüncü gezegendir.',
      category: 'Uzay',
    ),
    WordHuntInfoCard(
      id: 'info-pusula',
      word: 'PUSULA',
      title: 'Pusula',
      shortFact: 'Pusula, yön bulmaya yardımcı olan bir araçtır.',
      category: 'Keşif',
    ),
  ];

  static const WordHuntRouteDefinition baslangicLimani = WordHuntRouteDefinition(
    id: 'baslangic-limani',
    title: 'Başlangıç Limanı',
    theme: 'liman',
    unlockStarsRequired: 18,
    routeRewardId: 'badge-kelime-yolcusu',
    levels: <WordHuntLevelDefinition>[
      WordHuntLevelDefinition(
        id: 'baslangic-1',
        routeId: 'baslangic-limani',
        index: 1,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'KALEMS',
          'MASALI',
          'ELMALI',
          'BİLGİN',
          'OYUNCU',
          'ROTASI',
        ],
        targetWords: <String>['KALEM', 'MASA'],
        bonusWords: <String>['ELMA'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-2',
        routeId: 'baslangic-limani',
        index: 2,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'DDLELA',
          'EUEEİM',
          'NSGAML',
          'İIAIAG',
          'ZİAANİ',
          'İGEMİD',
        ],
        targetWords: <String>['DENİZ', 'GEMİ'],
        bonusWords: <String>['LİMAN'],
        infoCardIds: <String>['info-deniz'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-3',
        routeId: 'baslangic-limani',
        index: 3,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'GRİÖNY',
          'FPATİK',
          'LIDOSD',
          'USNÖBB',
          'KİCIRG',
          'OCADSİ',
        ],
        targetWords: <String>['KİTAP', 'OKUL'],
        bonusWords: <String>['SINIF'],
        infoCardIds: <String>['info-kitap'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-4',
        routeId: 'baslangic-limani',
        index: 4,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'HCHYNF',
          'SIYSÇZ',
          'BDZUYA',
          'EOÇLHM',
          'BAENIA',
          'KERÜSN',
        ],
        targetWords: <String>['HIZLI', 'ZAMAN'],
        bonusWords: <String>['SÜRE'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-5',
        routeId: 'baslangic-limani',
        index: 5,
        type: WordHuntLevelType.challenge,
        grid: <String>[
          'AAKİİŞ',
          'ENÜERE',
          'YEKEÜH',
          'KLNAEİ',
          'EATŞRR',
          'ELAKAA',
        ],
        targetWords: <String>['ANKARA', 'ŞEHİR'],
        bonusWords: <String>['KALE'],
        infoCardIds: <String>['info-ankara'],
        timeLimitSeconds: 60,
        starRules: WordHuntStarRules(
          twoStarMaxSeconds: 50,
          threeStarMaxSeconds: 35,
          twoStarMaxMistakes: 1,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-6',
        routeId: 'baslangic-limani',
        index: 6,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'İNAMRO',
          'TOPÇLŞ',
          'İKNAEA',
          'ŞÇĞKŞĞ',
          'AOYOKA',
          'DEHHNÇ',
        ],
        targetWords: <String>['DOĞA', 'ORMAN'],
        bonusWords: <String>['AĞAÇ'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-7',
        routeId: 'baslangic-limani',
        index: 7,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'ELLABP',
          'NEEPNK',
          'PDOKEA',
          'VNIÇAP',
          'ERİKLV',
          'AÇPADĞ',
        ],
        targetWords: <String>['ARI', 'ÇİÇEK'],
        bonusWords: <String>['BAL'],
        infoCardIds: <String>['info-ari'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-8',
        routeId: 'baslangic-limani',
        index: 8,
        type: WordHuntLevelType.bonus,
        grid: <String>[
          'SAAAIA',
          'KPZKHR',
          'YAOUAA',
          'ILORİP',
          'ZAUTKO',
          'IUŞOKT',
        ],
        targetWords: <String>['SPOR', 'TOP'],
        bonusWords: <String>['KOŞU'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-9',
        routeId: 'baslangic-limani',
        index: 9,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'NRIZDN',
          'NSONÜR',
          'YYRKGE',
          'AÖEAEY',
          'ZÜÜÜMT',
          'UZEGÜL',
        ],
        targetWords: <String>['MARS', 'UZAY'],
        bonusWords: <String>['ROKET'],
        infoCardIds: <String>['info-mars'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-10',
        routeId: 'baslangic-limani',
        index: 10,
        type: WordHuntLevelType.routeFinal,
        grid: <String>[
          'PUSULA',
          'KİYABT',
          'EEOİİN',
          'YILDIZ',
          'AGHAİE',
          'İKKERE',
        ],
        targetWords: <String>['PUSULA', 'YOL', 'BİLGİ'],
        bonusWords: <String>['YILDIZ'],
        infoCardIds: <String>['info-pusula'],
        timeLimitSeconds: 120,
        starRules: WordHuntStarRules(
          twoStarMaxSeconds: 100,
          threeStarMaxSeconds: 75,
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
    ],
  );
}
