import 'word_hunt_models.dart';

class WordHuntStarterContent {
  WordHuntStarterContent._();

  static const List<WordHuntInfoCard> infoCards = <WordHuntInfoCard>[
    WordHuntInfoCard(
      id: 'info-deniz',
      word: 'DENİZ',
      title: 'Deniz',
      shortFact: 'Deniz suyu, çözünmüş tuzlar nedeniyle genellikle tuzludur.',
      category: 'Doğa',
    ),
    WordHuntInfoCard(
      id: 'info-kitap',
      word: 'KİTAP',
      title: 'Kitap',
      shortFact: 'Kitaplar bilgi, öykü ve fikirleri kalıcı olarak aktarmanın yollarından biridir.',
      category: 'Kültür',
    ),
    WordHuntInfoCard(
      id: 'info-ankara',
      word: 'ANKARA',
      title: 'Ankara',
      shortFact: 'Ankara, Türkiye’nin başkentidir.',
      category: 'Türkiye',
    ),
    WordHuntInfoCard(
      id: 'info-ari',
      word: 'ARI',
      title: 'Arı',
      shortFact: 'Arılar, birçok çiçekli bitkinin tozlaşmasına yardımcı olur.',
      category: 'Doğa',
    ),
    WordHuntInfoCard(
      id: 'info-mars',
      word: 'MARS',
      title: 'Mars',
      shortFact: 'Mars, Güneş’e uzaklık bakımından dördüncü gezegendir.',
      category: 'Uzay',
    ),
    WordHuntInfoCard(
      id: 'info-pusula',
      word: 'PUSULA',
      title: 'Pusula',
      shortFact: 'Pusula, yön bulmaya yardımcı olan bir araçtır.',
      category: 'Keşif',
    ),
  ];

  static const WordHuntRouteDefinition baslangicLimani = WordHuntRouteDefinition(
    id: 'baslangic-limani',
    title: 'Başlangıç Limanı',
    theme: 'liman',
    unlockStarsRequired: 18,
    routeRewardId: 'badge-kelime-yolcusu',
    levels: <WordHuntLevelDefinition>[
      WordHuntLevelDefinition(
        id: 'baslangic-1',
        routeId: 'baslangic-limani',
        index: 1,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'KALEMS',
          'MASALI',
          'ELMALI',
          'BİLGİN',
          'OYUNCU',
          'ROTASI',
        ],
        targetWords: <String>['KALEM', 'MASA'],
        bonusWords: <String>['ELMA'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-2',
        routeId: 'baslangic-limani',
        index: 2,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'SFDÖLL',
          'AGEMİD',
          'EDNAMY',
          'ÜYİBAA',
          'IĞZCNK',
          'DALGAL',
        ],
        targetWords: <String>['DENİZ', 'GEMİ', 'DALGA'],
        bonusWords: <String>['LİMAN'],
        infoCardIds: <String>['info-deniz'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-3',
        routeId: 'baslangic-limani',
        index: 3,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'SFÖLAD',
          'FPATİK',
          'EIDAYL',
          'ÜYNBAU',
          'IĞCIKK',
          'LDERSO',
        ],
        targetWords: <String>['KİTAP', 'OKUL', 'DERS'],
        bonusWords: <String>['SINIF'],
        infoCardIds: <String>['info-kitap'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-4',
        routeId: 'baslangic-limani',
        index: 4,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'HEDEFK',
          'ZISFUÖ',
          'ALZBAD',
          'MEALDA',
          'AÇYÜIY',
          'NERÜSB',
        ],
        targetWords: <String>['HIZLI', 'ZAMAN', 'HEDEF', 'ÇABUK'],
        bonusWords: <String>['SÜRE'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-5',
        routeId: 'baslangic-limani',
        index: 5,
        type: WordHuntLevelType.challenge,
        grid: <String>[
          'ATAİŞM',
          'RNEÖEE',
          'NEKLHL',
          'YKSAİA',
          'KVPARK',
          'IİKNIA',
        ],
        targetWords: <String>['ANKARA', 'ŞEHİR', 'KENT', 'PARK'],
        bonusWords: <String>['KALE'],
        infoCardIds: <String>['info-ankara'],
        timeLimitSeconds: 60,
        starRules: WordHuntStarRules(
          twoStarMaxSeconds: 50,
          threeStarMaxSeconds: 35,
          twoStarMaxMistakes: 1,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-6',
        routeId: 'baslangic-limani',
        index: 6,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'NAMROK',
          'YSFÖAA',
          'LEADĞR',
          'EDŞOAP',
          'AYDİÇO',
          'ÜYBALT',
        ],
        targetWords: <String>['DOĞA', 'ORMAN', 'TOPRAK', 'YEŞİL'],
        bonusWords: <String>['AĞAÇ'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-7',
        routeId: 'baslangic-limani',
        index: 7,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'SFÖLAK',
          'DPETEK',
          'EDAÇYO',
          'ÜYİBIV',
          'AÇIRĞA',
          'CLABKN',
        ],
        targetWords: <String>['ARI', 'ÇİÇEK', 'PETEK', 'KOVAN'],
        bonusWords: <String>['BAL'],
        infoCardIds: <String>['info-ari'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-8',
        routeId: 'baslangic-limani',
        index: 8,
        type: WordHuntLevelType.bonus,
        grid: <String>[
          'SFGÖLZ',
          'AODEDI',
          'LSAYPH',
          'ÜYPBOA',
          'NUYOTI',
          'UŞOKRĞ',
        ],
        targetWords: <String>['SPOR', 'TOP', 'OYUN', 'HIZ'],
        bonusWords: <String>['KOŞU', 'GOL'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-9',
        routeId: 'baslangic-limani',
        index: 9,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'YRSSFÖ',
          'ALORAD',
          'ZYEKAD',
          'UANYEM',
          'ŞENÜGT',
          'ÜYUYDU',
        ],
        targetWords: <String>['MARS', 'UZAY', 'GÜNEŞ', 'DÜNYA', 'UYDU'],
        bonusWords: <String>['ROKET'],
        infoCardIds: <String>['info-mars'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-10',
        routeId: 'baslangic-limani',
        index: 10,
        type: WordHuntLevelType.routeFinal,
        grid: <String>[
          'BFMAEN',
          'GİEŞSL',
          'YILDIZ',
          'OÖGGET',
          'LYNLİH',
          'ALUSUP',
        ],
        targetWords: <String>['PUSULA', 'YOL', 'BİLGİ', 'YÖN', 'HEDEF'],
        bonusWords: <String>['YILDIZ'],
        infoCardIds: <String>['info-pusula'],
        timeLimitSeconds: 120,
        starRules: WordHuntStarRules(
          twoStarMaxSeconds: 100,
          threeStarMaxSeconds: 75,
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
    ],
  );
}
