group = "com.leventua.bilgirotasi.admobconfig"
version = "1.0-SNAPSHOT"

apply plugin: "com.android.library"

android {
    namespace = "com.leventua.bilgirotasi.admobconfig"
    compileSdk = flutter.compileSdkVersion

    defaultConfig {
        minSdk = 23
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}
